Minimal changes to build project using debian bookworm and ...
... pangolin 0.9.3

NB: the build must be done with g++-11 to avoid the following compilation
error, which is apparently a false positive emitted by g++-12:

    /usr/lib/gcc/x86_64-linux-gnu/12/include/xmmintrin.h:934:23: error: array subscript ‘__m128_u[0]’ is partly outside array bounds of ‘Sophus::Vector<float, 2, 0> [1]’ {aka ‘Eigen::Matrix<float, 2, 1> [1]’} [-Werror=array-bounds]
      934 |   return *(__m128_u *)__P;
          |                       ^~~
    In file included from /home/tim2/src/ORB_SLAM3/Thirdparty/Sophus/test/core/test_sim2.cpp:5:
    /home/tim2/src/ORB_SLAM3/Thirdparty/Sophus/sophus/sim2.hpp: In member function ‘Sophus::Vector<typename Eigen::internal::traits<T>::Scalar, 4> Sophus::Sim2Base<Derived>::params() const [with Derived = Sophus::Sim2<float>]’:
    /home/tim2/src/ORB_SLAM3/Thirdparty/Sophus/sophus/sim2.hpp:261:24: note: at offset [0, 4] into object ‘<anonymous>’ of size 8
      261 |     p << rxso2().params(), translation();
          |          ~~~~~~~~~~~~~~^~
      [...]

Here are links to two relevant issues on public trackers:

    [1] https://github.com/strasdat/Sophus/issues/531
    [2] https://gitlab.com/libeigen/eigen/-/issues/2506

This is the full command I used to build the project (after building and
installing Pangolin to ~/.local/lib/):

    env CC=gcc-11 CXX=g++-11 Pangolin_DIR=~/.local/lib/cmake/Pangolin/ ./build.sh